name: CI

on:
  pull_request:
    branches: [ vernBranch ]

  workflow_dispatch:

env:
  MYSQL_VERSION: 8.0.23
  MYSQL_DB: education_center
  MYSQL_USER: root
  MYSQL_PASSWORD: 2apples2
  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.23
        env:
          MYSQL_DB: ${{ env.MYSQL_DB }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend
