name: CI

on:
  pull_request:
    branches: [ vernBranch ]

  workflow_dispatch:

env:
  MYSQL_VERSION: 8.0.23
  MYSQL_DB: education_center
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: 2apples2
  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: 2apples2
          MYSQL_DATABASE: education_center
          MYSQL_ROOT_PASSWORD: 2apples2
        ports:
          - 3307:3306
          options: --health-cmd "mysqladmin ping" --health-interval=5s --health-timeout=5s --health-retries=5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend
