name: CI

on:
  pull_request:
    branches: [ vernBranch ]

  workflow_dispatch:

env:

  JAVA_VERSION: 1.15

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql/mysql-server:8.0.23
        env:
          MYSQL_DATABASE: education-center
          MYSQL_USER: root
          MYSQL_PASSWORD: 2apples2
          MYSQL_ROOT_PASSWORD: 2apples2
        ports:
          - 33307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Maven Clean Package
        run: |
          ./mvnw --no-transfer-progress clean package -P build-frontend
